import { applyDecorators } from '@nestjs/common';
import { ApiOperation, ApiResponse } from '@nestjs/swagger';

export const GetQuestionSwagger = () =>
  applyDecorators(
    ApiOperation({ summary: '질문 정보 조회' }),
    ApiResponse({
      status: 200,
      description: '질문 조회 성공',
      schema: {
        example: {
          questions: [
            {
              question_id: 1,
              session_id: '672e1c17-dcd4-8010-927c-84369a530f29',
              body: 'Question 1 body',
              closed: false,
              pinned: false,
              created_at: '2024-11-11T16:03:39.915Z',
              isOwner: false,
              likesCount: 3,
              hasLiked: true,
              nickname: 'user1',
              replies: [
                {
                  reply_id: 1,
                  body: 'Reply 1 to Question 1',
                  created_at: '2024-11-11T16:04:02.532Z',
                  isOwner: false,
                  likesCount: 0,
                  hasLiked: false,
                  nickname: 'user1',
                },
                {
                  reply_id: 5,
                  body: '인정합니다. 역시 대지호님이시네요',
                  created_at: '2024-11-12T17:45:42.770Z',
                  isOwner: false,
                  likesCount: 0,
                  hasLiked: false,
                  nickname: 'user1',
                },
                {
                  reply_id: 4,
                  body: '역시 대지호님이시네요',
                  created_at: '2024-11-12T15:20:47.711Z',
                  isOwner: false,
                  likesCount: 0,
                  hasLiked: false,
                  nickname: 'user1',
                },
              ],
            },
            {
              question_id: 2,
              session_id: '672e1c17-dcd4-8010-927c-84369a530f29',
              body: 'Question 2 body',
              closed: false,
              pinned: false,
              created_at: '2024-11-11T16:03:39.915Z',
              isOwner: true,
              likesCount: 1,
              hasLiked: true,
              nickname: '익명',
              replies: [
                {
                  reply_id: 2,
                  body: 'Reply 2 to Question 2',
                  created_at: '2024-11-11T16:04:02.532Z',
                  isOwner: true,
                  likesCount: 1,
                  hasLiked: true,
                  nickname: '익명',
                },
              ],
            },
            {
              question_id: 3,
              session_id: '672e1c17-dcd4-8010-927c-84369a530f29',
              body: 'Question 3 body',
              closed: false,
              pinned: false,
              created_at: '2024-11-11T16:03:39.915Z',
              isOwner: true,
              likesCount: 1,
              hasLiked: true,
              nickname: '익명',
              replies: [],
            },
            {
              question_id: 4,
              session_id: '672e1c17-dcd4-8010-927c-84369a530f29',
              body: '대지호',
              closed: false,
              pinned: false,
              created_at: '2024-11-12T09:37:01.601Z',
              isOwner: true,
              likesCount: 0,
              hasLiked: false,
              nickname: '익명',
              replies: [
                {
                  reply_id: 10,
                  body: '그저 대지호 ㄷㄷ',
                  created_at: '2024-11-13T08:49:55.624Z',
                  isOwner: true,
                  likesCount: 0,
                  hasLiked: false,
                  nickname: '익명',
                },
              ],
            },
            {
              question_id: 8,
              session_id: '672e1c17-dcd4-8010-927c-84369a530f29',
              body: '아닙니다.',
              closed: false,
              pinned: false,
              created_at: '2024-11-14T05:50:26.613Z',
              isOwner: true,
              likesCount: 0,
              hasLiked: false,
              nickname: '익명',
              replies: [],
            },
            {
              question_id: 6,
              session_id: '672e1c17-dcd4-8010-927c-84369a530f29',
              body: '하이하이',
              closed: false,
              pinned: false,
              created_at: '2024-11-14T05:47:54.079Z',
              isOwner: true,
              likesCount: 0,
              hasLiked: false,
              nickname: '익명',
              replies: [],
            },
            {
              question_id: 5,
              session_id: '672e1c17-dcd4-8010-927c-84369a530f29',
              body: '나는 누구인가',
              closed: true,
              pinned: false,
              created_at: '2024-11-14T05:31:18.540Z',
              isOwner: true,
              likesCount: 0,
              hasLiked: false,
              nickname: '익명',
              replies: [],
            },
            {
              question_id: 9,
              session_id: '672e1c17-dcd4-8010-927c-84369a530f29',
              body: '하이하이',
              closed: false,
              pinned: true,
              created_at: '2024-11-14T12:56:27.021Z',
              isOwner: true,
              likesCount: 0,
              hasLiked: false,
              nickname: '익명',
              replies: [],
            },
          ],
        },
      },
    }),
  );
